### ISSUE TITLE
Add domain independent agent parameter slider in HMI

### ISSUE THREAD

**Issue by MrLoNee** [MrLoNee/SketchFX#7]

**Comment by ofmooseandmen** [comment]
API needs tout ne review after last commit see code for more info)

**Comment by ofmooseandmen** [comment]
Actually parameters should be passed to the agent otherwise they cannot modify the values specific to each recognizers.

final class AgentParameters () {

   CircleParameters circle() {
      return circle;
    }

```
LineParameters line() {
   return line
}
```

}

Each recognizer parameter shall be passed to the relevant recognizer and provide sensible default values. Each recognizer shall keep a reference to its parameter and retrieve param values on the fly.

This way the user can modify the value of each parameter from the outside and the changes would reflect on each recognizer

**Comment by MrLoNee** [comment]
Done.
Default Parameters value are accessible through the API of each parameter interface.
Slider added. For now it is in default mode, but chead mode based on System.getProperty("cheat.mode") could be used when releasing a version.
